spring:
  cloud:
    config:
      name: account-service
      profile: ${spring.profiles.active:local}
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}
  output:
    ansi:
      enabled: always
